

---
- name: Make sure the relevant directories exist for deployment
  file: path="/opt/peba" owner=root group=root mode=0755 recurse=yes state=directory

- name: Create ews config dir
  file: path="/etc/ews/" owner=root group=root mode=0755 recurse=yes state=directory


- name: Copy scripts
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: './../../../../peba.py', dest: '/opt/peba/peba.py' }
    - { src: './../../../../requirements.txt', dest: '/opt/peba/requirements.txt' }

- name: install configuration file
  template:
        src=./roles/peba/templates/peba.cfg
        dest='/etc/ews/peba.cfg'

- name: Install init.d script
  copy:
    src: './../../../../etc/init.d/peba'
    dest: '/etc/init.d/peba'
    mode: 0755

- name: Reload daemon
  shell: "systemctl daemon-reload"

- name: Install necessary packages.
  apt: name={{ item }} state=present
  with_items:
    - nano
    - wget
    - curl
    - unzip
    - python-pip
    - build-essential
    - autoconf
    - libtool
    - pkg-config
    - python-dev
    - python3-dev
    - python3-pip
    - python3-venv


- name: Add user peba.
  user:
    name: peba
    shell: /bin/nologin
    home: /nonexistent
    createhome: no
    system: yes
    comment: user for peba backend service

- name: Installing virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: Install pip requirements
  pip:
    requirements: /opt/peba/requirements.txt
    state: latest
    virtualenv_command: pyvenv
    virtualenv: /opt/peba/


- name: Start peba service
  service:
    name: peba
    enabled: yes
    state: restarted
